build: fix some bug
Signed-off-by: Jiamu Sun <barroit@linux.com>

diff --git a/brtool-src/command/build b/brtool-src/command/build
--- a/brtool-src/command/build
+++ b/brtool-src/command/build
@@ -1,43 +1,55 @@
-#!/usr/bin/bash
-# you should NEVER execute this file manually, or you may get unexpected side effects
+export BUILD_PROFILE="${1:-debug}"
+export PROGRAM_HOST="${2:-penguin}"
 
-build_type="${1:-debug}"
-target_platform="${2:-penguin}"
-
-if ! find_array_element "$build_type" "$BRTOOL_BUILD_TYPES"
+if ! find_scalar_word "$BUILD_PROFILE" "$BRTOOL_BUILD_PROFILES"
 then
-	die "build type '$build_type' not found"
+	die "build type '$BUILD_PROFILE' not found"
 fi
 
-build_prefix="$BRTOOL_BUILD_PREFIX"/"$build_type"
-
-source "$BRTOOL_SRC_PREFIX"/depstat
-
-if ! command "$BRTOOL_SRC_PREFIX"/make_openssl "$target_platform"
+if ! find_scalar_word "$PROGRAM_HOST" "$BRTOOL_PROGRAM_HOSTS"
 then
-	die 'stop building'
+	die "build type '$PROGRAM_HOST' not found"
 fi
 
-if ! command "$BRTOOL_SRC_PREFIX"/make_sqlcipher "$target_platform"
+build_prefix="$BRTOOL_BUILD_PREFIX"/"$BUILD_PROFILE"
+
+source "$BRTOOL_SOURCE_PREFIX"/depstat
+
+if ! bash "$BRTOOL_SOURCE_PREFIX"/make_openssl
 then
 	die 'stop building'
 fi
 
-exit 1
+if ! bash "$BRTOOL_SOURCE_PREFIX"/make_sqlcipher
+then
+	die 'stop building'
+fi
+
 load_project_info
 
-if ! depstat_match_prev 'cmake' "$target_platform"
+if ! depstat_match_prev 'cmake' "$PROGRAM_HOST" && [[ -d "$build_prefix" ]]
 then
-	rm -rf $build_prefix
+	rm -r $build_prefix/*
 fi
 
-echo "-- Build type: $build_type"
-echo "-- Target platform: $target_platform"
+echo "-- Build profile: $BUILD_PROFILE"
+echo "-- Host name: $PROGRAM_HOST"
 
-cmake -B $build_prefix \
--DCMAKE_TARGET_PLATFORM=${target_platform^} \
--DCMAKE_BUILD_TYPE=${build_type^} -DINSTALL_PREFIX=$BRTOOL_INSTALL_PREFIX
+export PKG_CONFIG_PATH="${LIBRARY_INSTALL_PREFIX}/lib64/pkgconfig:\
+${LIBRARY_INSTALL_PREFIX}/lib/pkgconfig"
 
-cmake --build "$build_prefix" --parallel 25
+mkdir -p "$build_prefix"
+cd "$build_prefix"
 
-update_depstat_record 'cmake' "$target_platform"
+if [[ "$PROGRAM_HOST" == 'window' ]]
+then
+	cmake_options="-DCMAKE_TOOLCHAIN_FILE='$CMAKE_MODULE_PREFIX/MinGW-w64.cmake'"
+else
+	cmake_options="-DCMAKE_TOOLCHAIN_FILE='$CMAKE_MODULE_PREFIX/GCC.cmake'"
+fi
+
+cmake "$PROJECT_PREFIX" -DCMAKE_BUILD_TYPE="${BUILD_PROFILE^}" "$cmake_options"
+
+make -j25
+
+update_depstat_record 'cmake' "$PROGRAM_HOST"
diff --git a/brtool-src/uihandle b/brtool-src/uihandle
--- a/brtool-src/uihandle
+++ b/brtool-src/uihandle
@@ -1,18 +1,16 @@
-#/usr/bin/bash
-
-temp_stderr=$(mktemp)
-exec 3>/dev/null
-failed=0
+current_time()
+{
+	date +%s%N | cut -b1-13
+}
 
 spinner()
 {
-	local pid=$!
 	local spin='-\|/'
 	local i=0
 
-	while kill -0 $pid 2>/dev/null
+	while kill -0 "$1" 2>/dev/null
 	do
-		i=$(((i + 1) % 4))
+		i=$(( (i + 1) % 4 ))
 		printf '%s\b' "${spin:$i:1}"
 		sleep .2
 	done
@@ -23,25 +21,36 @@ process_start()
 	printf -- '-- %s... ' "$*"
 }
 
-process_exec() {
-	eval "$*" 2> >(grep -v "WARNING" > $temp_stderr) >&3 & spinner
+process_exec()
+{
+	process_exec_starts_at=$(current_time)
+
+	eval $* > /dev/null 2>&1 &
+	local cmd_pid=$!
+
+	spinner "$cmd_pid"
+
+	wait "$cmd_pid"
+
+	return $?
 }
 
 process_end()
 {
-	if [[ -s $temp_stderr ]]
-	then
-		echo 'no'
-		cat $temp_stderr >&2
-		truncate -s 0 $temp_stderr
-		failed=1
-	else
-		echo 'ok'
-	fi
-}
+	local rescode=$?
 
-process_cleanup()
-{
-	rm $temp_stderr
-	exit $failed
+	if [[ $rescode != 0 ]]
+	then
+		echo "no (result: $rescode)"
+
+		if [[ $rescode -eq 77 || $rescode -eq 2 ]]
+		then
+			echo 'error: compiler internal failure, try to adjust jobs or run this command again'
+		fi
+
+		exit $rescode
+	else
+		elapsed_time="$(bc <<< "scale=1; ($(current_time) - $process_exec_starts_at) / 1000")"
+		printf "ok (%.1fs)\n" "$elapsed_time"
+	fi
 }
